#
# Module manifest for module 'RSR'
#
# Generated by: RSR
# Generated on: 2024-12-11
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'RSR.psm1'

    # Version number of this module.
    ModuleVersion = '2.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

    # Author of this module
    Author = 'RSR Team'

    # Company or vendor of this module
    CompanyName = 'Pandia'

    # Copyright statement for this module
    Copyright = '(c) 2024 Pandia. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Remote Script Runner (RSR) PowerShell Library - Cross-platform system administration utilities'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @(
        'Core\RSR.Core.psm1',
        'Core\RSR.Validate.psm1',
        'Core\RSR.Interactive.psm1',
        'Modules\RSR.Users.psm1',
        'Modules\RSR.Docker.psm1',
        'Modules\RSR.SSH.psm1'
    )

    # Functions to export from this module, for best performance, do not use wildcards
    FunctionsToExport = @(
        # Core functions
        'Write-RSRLog',
        'Write-RSRInfo',
        'Write-RSROk',
        'Write-RSRWarn',
        'Write-RSRError',
        'Write-RSRDebug',
        'Write-RSRHeader',
        'Get-RSRPlatform',
        'Get-RSRArchitecture',
        'Get-RSRDistro',
        'Test-RSRCommand',
        'Invoke-RSRDownload',
        'Test-RSRRoot',
        'Assert-RSRRoot',

        # Validation functions
        'Test-RSRUsername',
        'Test-RSRPassword',
        'Test-RSRPasswordComplex',
        'Test-RSRIPv4',
        'Test-RSRIPv6',
        'Test-RSRHostname',
        'Test-RSRPort',
        'Test-RSREmail',
        'Test-RSRUrl',

        # Interactive functions
        'Read-RSRConfirm',
        'Read-RSRInput',
        'Read-RSRPassword',
        'Read-RSRSelect',
        'Read-RSRMultiSelect',
        'Show-RSRProgress',
        'Show-RSRSpinner',

        # User functions
        'Test-RSRUserExists',
        'Get-RSRUser',
        'Get-RSRUserInfo',
        'Get-RSRUsers',
        'Get-RSRHumanUsers',
        'New-RSRUser',
        'Remove-RSRUser',
        'Enable-RSRUser',
        'Disable-RSRUser',
        'Set-RSRUserPassword',
        'New-RSRRandomPassword',
        'Test-RSRGroupExists',
        'Get-RSRGroups',
        'New-RSRGroup',
        'Remove-RSRGroup',
        'Add-RSRGroupMember',
        'Remove-RSRGroupMember',
        'Get-RSRUserGroups',
        'Test-RSRUserHasSudo',
        'Grant-RSRUserSudo',
        'Revoke-RSRUserSudo',

        # Docker functions
        'Test-RSRDockerInstalled',
        'Test-RSRDockerRunning',
        'Assert-RSRDocker',
        'Get-RSRDockerVersion',
        'Get-RSRDockerContainers',
        'Test-RSRDockerContainerExists',
        'Test-RSRDockerContainerRunning',
        'Start-RSRDockerContainer',
        'Stop-RSRDockerContainer',
        'Restart-RSRDockerContainer',
        'Remove-RSRDockerContainer',
        'Get-RSRDockerContainerLogs',
        'Invoke-RSRDockerExec',
        'Get-RSRDockerImages',
        'Get-RSRDockerImage',
        'Remove-RSRDockerImage',
        'Get-RSRDockerVolumes',
        'New-RSRDockerVolume',
        'Remove-RSRDockerVolume',
        'Get-RSRDockerNetworks',
        'New-RSRDockerNetwork',
        'Remove-RSRDockerNetwork',
        'Invoke-RSRDockerSystemPrune',

        # SSH functions
        'Test-RSRSSHServerInstalled',
        'Test-RSRSSHServerRunning',
        'Test-RSRSSHServerEnabled',
        'Get-RSRSSHServerStatus',
        'Start-RSRSSHServer',
        'Stop-RSRSSHServer',
        'Restart-RSRSSHServer',
        'Enable-RSRSSHServer',
        'Disable-RSRSSHServer',
        'New-RSRSSHKey',
        'Get-RSRSSHPublicKey',
        'Add-RSRSSHAuthorizedKey',
        'Remove-RSRSSHAuthorizedKey',
        'Get-RSRSSHAuthorizedKeys'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @(
        'RSR_VERSION',
        'RSR_EXIT_SUCCESS',
        'RSR_EXIT_ERROR',
        'RSR_EXIT_USAGE',
        'RSR_EXIT_DEPENDENCY',
        'RSR_EXIT_PERMISSION',
        'RSR_EXIT_NOT_FOUND',
        'RSR_EXIT_ALREADY_EXISTS'
    )

    # Aliases to export from this module
    AliasesToExport = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module
            Tags = @('RSR', 'SysAdmin', 'Automation', 'CrossPlatform', 'UserManagement', 'Docker', 'SSH')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/codefuturist/remote-script-runner/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/codefuturist/remote-script-runner'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = 'Version 2.0.0 - Complete rewrite with modular architecture'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module
    # DefaultCommandPrefix = 'RSR'
}

